// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_start
void ui_start_screen_init(void);
lv_obj_t *ui_start;
lv_obj_t *ui_header3;
void ui_event_logo1( lv_event_t * e);
lv_obj_t *ui_logo1;
lv_obj_t *ui_Status3;
lv_obj_t *ui_groundstationIndicator;
lv_obj_t *ui_groundstationStatus;
// CUSTOM VARIABLES

// SCREEN: ui_dashboard
void ui_dashboard_screen_init(void);
lv_obj_t *ui_dashboard;
lv_obj_t *ui_header;
lv_obj_t *ui_item1;
lv_obj_t *ui_headlightValue;
lv_obj_t *ui_Label1;
lv_obj_t *ui_modeValue;
lv_obj_t *ui_Label2;
lv_obj_t *ui_mode;
lv_obj_t *ui_straight;
lv_obj_t *ui_three60;
lv_obj_t *ui_normal;
// CUSTOM VARIABLES
lv_obj_t *uic_aw;

// SCREEN: ui_stats
void ui_stats_screen_init(void);
lv_obj_t *ui_stats;
lv_obj_t *ui_header1;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Container8;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Status1;
lv_obj_t *ui_imuIndicator;
lv_obj_t *ui_imuStatus;
lv_obj_t *ui_Container9;
lv_obj_t *ui_Container7;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Container10;
lv_obj_t *ui_rollValue;
lv_obj_t *ui_Container2;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Container11;
lv_obj_t *ui_pitchValue;
lv_obj_t *ui_Container3;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Container12;
lv_obj_t *ui_yawValue;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Status;
lv_obj_t *ui_encoderIndicator;
lv_obj_t *ui_encoderStatus;
lv_obj_t *ui_Label12;
lv_obj_t *ui_encoderValue;
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Status2;
lv_obj_t *ui_wifiIndicator;
lv_obj_t *ui_wifiStatus;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Label23;
// CUSTOM VARIABLES

// SCREEN: ui_altius
void ui_altius_screen_init(void);
lv_obj_t *ui_altius;
lv_obj_t *ui_header2;
lv_obj_t *ui_Container13;
lv_obj_t *ui_Container14;
lv_obj_t *ui_Container17;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Container16;
lv_obj_t *ui_Label26;
lv_obj_t *ui_Container19;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Container20;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Container15;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Container21;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Container22;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Container23;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Container18;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Image16;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_logo1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dashboard_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_start_screen_init();
ui_dashboard_screen_init();
ui_stats_screen_init();
ui_altius_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_start);
}
