// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#ifndef _ARNOBOT_GROUNDSTATION_UI_H
#define _ARNOBOT_GROUNDSTATION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_start
void ui_start_screen_init(void);
extern lv_obj_t *ui_start;
extern lv_obj_t *ui_header3;
void ui_event_logo1( lv_event_t * e);
extern lv_obj_t *ui_logo1;
extern lv_obj_t *ui_Status3;
extern lv_obj_t *ui_groundstationIndicator;
extern lv_obj_t *ui_groundstationStatus;
// CUSTOM VARIABLES

// SCREEN: ui_dashboard
void ui_dashboard_screen_init(void);
extern lv_obj_t *ui_dashboard;
extern lv_obj_t *ui_header;
extern lv_obj_t *ui_item1;
extern lv_obj_t *ui_headlightValue;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_modeValue;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_mode;
extern lv_obj_t *ui_straight;
extern lv_obj_t *ui_three60;
extern lv_obj_t *ui_normal;
// CUSTOM VARIABLES
extern lv_obj_t *uic_aw;

// SCREEN: ui_stats
void ui_stats_screen_init(void);
extern lv_obj_t *ui_stats;
extern lv_obj_t *ui_header1;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Status1;
extern lv_obj_t *ui_imuIndicator;
extern lv_obj_t *ui_imuStatus;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_rollValue;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_pitchValue;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_yawValue;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Status;
extern lv_obj_t *ui_encoderIndicator;
extern lv_obj_t *ui_encoderStatus;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_encoderValue;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Status2;
extern lv_obj_t *ui_wifiIndicator;
extern lv_obj_t *ui_wifiStatus;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Label23;
// CUSTOM VARIABLES

// SCREEN: ui_altius
void ui_altius_screen_init(void);
extern lv_obj_t *ui_altius;
extern lv_obj_t *ui_header2;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Container16;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_Container19;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_Container20;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Container15;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Container21;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Container22;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Container23;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Container18;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Image16;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_icon_colour_digital_png);   // assets/icon colour digital.png
LV_IMG_DECLARE( ui_img_horizontal_png);   // assets/horizontal.png
LV_IMG_DECLARE( ui_img_image_png);   // assets/image.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
