// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#include "ui.h"

void ui_altius_screen_init(void)
{
ui_altius = lv_obj_create(NULL);
lv_obj_clear_flag( ui_altius, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_header2 = ui_header_create(ui_altius);
lv_obj_set_x( ui_header2, -2 );
lv_obj_set_y( ui_header2, -209 );

ui_Container13 = lv_obj_create(ui_altius);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, 734);
lv_obj_set_height( ui_Container13, 209);
lv_obj_set_x( ui_Container13, 3 );
lv_obj_set_y( ui_Container13, 122 );
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xE4E2EB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container14 = lv_obj_create(ui_Container13);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, 365);
lv_obj_set_height( ui_Container14, 216);
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container14,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container14, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container14, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container17 = lv_obj_create(ui_Container14);
lv_obj_remove_style_all(ui_Container17);
lv_obj_set_width( ui_Container17, 360);
lv_obj_set_height( ui_Container17, 35);
lv_obj_set_x( ui_Container17, -154 );
lv_obj_set_y( ui_Container17, 59 );
lv_obj_set_align( ui_Container17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container17, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container17, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Container17);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"Range");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container16 = lv_obj_create(ui_Container14);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_width( ui_Container16, 360);
lv_obj_set_height( ui_Container16, 35);
lv_obj_set_x( ui_Container16, -154 );
lv_obj_set_y( ui_Container16, 59 );
lv_obj_set_align( ui_Container16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container16, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container16, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label26 = lv_label_create(ui_Container16);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"Control");
lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container19 = lv_obj_create(ui_Container14);
lv_obj_remove_style_all(ui_Container19);
lv_obj_set_width( ui_Container19, 360);
lv_obj_set_height( ui_Container19, 35);
lv_obj_set_x( ui_Container19, -154 );
lv_obj_set_y( ui_Container19, 59 );
lv_obj_set_align( ui_Container19, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container19, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container19, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_Container19);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"Weight");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container20 = lv_obj_create(ui_Container14);
lv_obj_remove_style_all(ui_Container20);
lv_obj_set_width( ui_Container20, 360);
lv_obj_set_height( ui_Container20, 35);
lv_obj_set_x( ui_Container20, -154 );
lv_obj_set_y( ui_Container20, 59 );
lv_obj_set_align( ui_Container20, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container20, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container20, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_Container20);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"Payload");
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container15 = lv_obj_create(ui_Container13);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_width( ui_Container15, 371);
lv_obj_set_height( ui_Container15, 208);
lv_obj_set_align( ui_Container15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container15,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 360);
lv_obj_set_height( ui_Container1, 35);
lv_obj_set_x( ui_Container1, -154 );
lv_obj_set_y( ui_Container1, 59 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"1000 m");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container21 = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_Container21);
lv_obj_set_width( ui_Container21, 360);
lv_obj_set_height( ui_Container21, 35);
lv_obj_set_x( ui_Container21, -154 );
lv_obj_set_y( ui_Container21, 59 );
lv_obj_set_align( ui_Container21, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container21, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container21, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label29 = lv_label_create(ui_Container21);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Wireless");
lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container22 = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_Container22);
lv_obj_set_width( ui_Container22, 360);
lv_obj_set_height( ui_Container22, 35);
lv_obj_set_x( ui_Container22, -154 );
lv_obj_set_y( ui_Container22, 59 );
lv_obj_set_align( ui_Container22, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container22, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container22, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Container22);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"17 Kg");
lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container23 = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_Container23);
lv_obj_set_width( ui_Container23, 360);
lv_obj_set_height( ui_Container23, 35);
lv_obj_set_x( ui_Container23, -154 );
lv_obj_set_y( ui_Container23, 59 );
lv_obj_set_align( ui_Container23, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container23, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container23, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label31 = lv_label_create(ui_Container23);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"20 kg");
lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container18 = lv_obj_create(ui_altius);
lv_obj_remove_style_all(ui_Container18);
lv_obj_set_width( ui_Container18, 735);
lv_obj_set_height( ui_Container18, 34);
lv_obj_set_x( ui_Container18, 4 );
lv_obj_set_y( ui_Container18, 0 );
lv_obj_set_align( ui_Container18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_Container18);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Bot Specifications");
lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image16 = lv_img_create(ui_altius);
lv_img_set_src(ui_Image16, &ui_img_image_png);
lv_obj_set_width( ui_Image16, LV_SIZE_CONTENT);  /// 301
lv_obj_set_height( ui_Image16, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image16, 4 );
lv_obj_set_y( ui_Image16, -99 );
lv_obj_set_align( ui_Image16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image16, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
