// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#include "ui.h"

void ui_event_comp_header_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_stats, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_stats_screen_init);
}
}

void ui_event_comp_header_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_start, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_start_screen_init);
}
}

void ui_event_comp_header_Label4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dashboard_screen_init);
}
}

void ui_event_comp_header_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dashboard_screen_init);
}
}

void ui_event_comp_header_Label32( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dashboard_screen_init);
}
}

void ui_event_comp_header_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_header = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_altius, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_altius_screen_init);
}
}

// COMPONENT header

lv_obj_t *ui_header_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_header;
cui_header = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_header);
lv_obj_set_width( cui_header, 806);
lv_obj_set_height( cui_header, 62);
lv_obj_set_x( cui_header, -2 );
lv_obj_set_y( cui_header, -209 );
lv_obj_set_align( cui_header, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_header, lv_color_hex(0x090A7C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_header, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Button4;
cui_Button4 = lv_btn_create(cui_header);
lv_obj_set_width( cui_Button4, 115);
lv_obj_set_height( cui_Button4, 62);
lv_obj_set_x( cui_Button4, 344 );
lv_obj_set_y( cui_Button4, 0 );
lv_obj_set_align( cui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Button4, lv_color_hex(0x3C9AEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(cui_Button4, lv_color_hex(0x562FF8), LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_t *cui_Label3;
cui_Label3 = lv_label_create(cui_header);
lv_obj_set_width( cui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label3, 347 );
lv_obj_set_y( cui_Label3, -1 );
lv_obj_set_align( cui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label3,"Stats");
lv_obj_set_style_text_color(cui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(cui_Label3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Image14;
cui_Image14 = lv_img_create(cui_header);
lv_img_set_src(cui_Image14, &ui_img_icon_colour_digital_png);
lv_obj_set_width( cui_Image14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Image14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Image14, -361 );
lv_obj_set_y( cui_Image14, 0 );
lv_obj_set_align( cui_Image14, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Button2;
cui_Button2 = lv_btn_create(cui_header);
lv_obj_set_width( cui_Button2, 100);
lv_obj_set_height( cui_Button2, 50);
lv_obj_set_x( cui_Button2, -233 );
lv_obj_set_y( cui_Button2, -2 );
lv_obj_set_align( cui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label4;
cui_Label4 = lv_label_create(cui_Button2);
lv_obj_set_width( cui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label4, -1 );
lv_obj_set_y( cui_Label4, 2 );
lv_obj_set_align( cui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label4,"HOME");
lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label4, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Button6;
cui_Button6 = lv_btn_create(cui_header);
lv_obj_set_width( cui_Button6, 150);
lv_obj_set_height( cui_Button6, 50);
lv_obj_set_x( cui_Button6, -72 );
lv_obj_set_y( cui_Button6, -1 );
lv_obj_set_align( cui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label32;
cui_Label32 = lv_label_create(cui_Button6);
lv_obj_set_width( cui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label32, -1 );
lv_obj_set_y( cui_Label32, 2 );
lv_obj_set_align( cui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label32,"Dashboard");
lv_obj_set_style_text_color(cui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label32, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Button3;
cui_Button3 = lv_btn_create(cui_header);
lv_obj_set_width( cui_Button3, 100);
lv_obj_set_height( cui_Button3, 50);
lv_obj_set_x( cui_Button3, 95 );
lv_obj_set_y( cui_Button3, -1 );
lv_obj_set_align( cui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label5;
cui_Label5 = lv_label_create(cui_Button3);
lv_obj_set_width( cui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label5, -2 );
lv_obj_set_y( cui_Label5, 1 );
lv_obj_set_align( cui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label5,"ALTIUS");
lv_obj_set_style_text_color(cui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label5, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
children[UI_COMP_HEADER_HEADER] = cui_header;
children[UI_COMP_HEADER_BUTTON4] = cui_Button4;
children[UI_COMP_HEADER_LABEL3] = cui_Label3;
children[UI_COMP_HEADER_IMAGE14] = cui_Image14;
children[UI_COMP_HEADER_BUTTON2] = cui_Button2;
children[UI_COMP_HEADER_BUTTON2_LABEL4] = cui_Label4;
children[UI_COMP_HEADER_BUTTON6] = cui_Button6;
children[UI_COMP_HEADER_BUTTON6_LABEL32] = cui_Label32;
children[UI_COMP_HEADER_BUTTON3] = cui_Button3;
children[UI_COMP_HEADER_BUTTON3_LABEL5] = cui_Label5;
lv_obj_add_event_cb(cui_header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_header, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Button4, ui_event_comp_header_Button4, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Label4, ui_event_comp_header_Label4, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Button2, ui_event_comp_header_Button2, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Label32, ui_event_comp_header_Label32, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Button6, ui_event_comp_header_Button6, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Button3, ui_event_comp_header_Button3, LV_EVENT_ALL, children);
ui_comp_header_create_hook(cui_header);
return cui_header; 
}

