// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_BUTTON4 1
#define UI_COMP_HEADER_LABEL3 2
#define UI_COMP_HEADER_IMAGE14 3
#define UI_COMP_HEADER_BUTTON2 4
#define UI_COMP_HEADER_BUTTON2_LABEL4 5
#define UI_COMP_HEADER_BUTTON6 6
#define UI_COMP_HEADER_BUTTON6_LABEL32 7
#define UI_COMP_HEADER_BUTTON3 8
#define UI_COMP_HEADER_BUTTON3_LABEL5 9
#define _UI_COMP_HEADER_NUM 10
lv_obj_t *ui_header_create(lv_obj_t *comp_parent);
void ui_event_comp_header_Button4( lv_event_t * e);
void ui_event_comp_header_Button2( lv_event_t * e);
void ui_event_comp_header_Label4( lv_event_t * e);
void ui_event_comp_header_Button6( lv_event_t * e);
void ui_event_comp_header_Label32( lv_event_t * e);
void ui_event_comp_header_Button3( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
