// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#include "ui.h"

void ui_dashboard_screen_init(void)
{
ui_dashboard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_dashboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_dashboard, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_dashboard, lv_color_hex(0x06097C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dashboard, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_header = ui_header_create(ui_dashboard);
lv_obj_set_x( ui_header, -2 );
lv_obj_set_y( ui_header, -209 );

ui_item1 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_item1);
lv_obj_set_width( ui_item1, 747);
lv_obj_set_height( ui_item1, 127);
lv_obj_set_x( ui_item1, -4 );
lv_obj_set_y( ui_item1, -85 );
lv_obj_set_align( ui_item1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_item1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_item1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_headlightValue = lv_switch_create(ui_item1);
lv_obj_set_width( ui_headlightValue, 201);
lv_obj_set_height( ui_headlightValue, 88);
lv_obj_set_x( ui_headlightValue, -228 );
lv_obj_set_y( ui_headlightValue, 2 );
lv_obj_set_align( ui_headlightValue, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_item1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 157 );
lv_obj_set_y( ui_Label1, 3 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Head Light ");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_modeValue = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_modeValue);
lv_obj_set_width( ui_modeValue, 747);
lv_obj_set_height( ui_modeValue, 127);
lv_obj_set_x( ui_modeValue, -2 );
lv_obj_set_y( ui_modeValue, 57 );
lv_obj_set_align( ui_modeValue, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_modeValue, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_modeValue, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_modeValue);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -242 );
lv_obj_set_y( ui_Label2, -33 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Drive Mode");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mode = lv_tabview_create(ui_modeValue, LV_DIR_TOP, 50);
lv_obj_set_width( ui_mode, 716);
lv_obj_set_height( ui_mode, 53);
lv_obj_set_x( ui_mode, 6 );
lv_obj_set_y( ui_mode, 28 );
lv_obj_set_align( ui_mode, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_straight = lv_tabview_add_tab(ui_mode, "straight");

ui_three60 = lv_tabview_add_tab(ui_mode, "360");

ui_normal = lv_tabview_add_tab(ui_mode, "normal");

uic_aw = ui_Label1;

}
