// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Arnobot_GroundStation

#include "ui.h"

void ui_stats_screen_init(void)
{
ui_stats = lv_obj_create(NULL);
lv_obj_clear_flag( ui_stats, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_header1 = ui_header_create(ui_stats);
lv_obj_set_x( ui_header1, -2 );
lv_obj_set_y( ui_header1, -209 );

ui_Container4 = lv_obj_create(ui_stats);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 772);
lv_obj_set_height( ui_Container4, 132);
lv_obj_set_x( ui_Container4, -2 );
lv_obj_set_y( ui_Container4, -87 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x777BE4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Container4, lv_color_hex(0xDED9D9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Container4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Container4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Container4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 768);
lv_obj_set_height( ui_Container8, 44);
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -337 );
lv_obj_set_y( ui_Label6, -1 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"IMU");

ui_Status1 = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_Status1);
lv_obj_set_width( ui_Status1, 141);
lv_obj_set_height( ui_Status1, 40);
lv_obj_set_x( ui_Status1, 312 );
lv_obj_set_y( ui_Status1, 0 );
lv_obj_set_align( ui_Status1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Status1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Status1, lv_color_hex(0xD3CDCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imuIndicator = lv_obj_create(ui_Status1);
lv_obj_set_width( ui_imuIndicator, 19);
lv_obj_set_height( ui_imuIndicator, 21);
lv_obj_set_x( ui_imuIndicator, -47 );
lv_obj_set_y( ui_imuIndicator, -3 );
lv_obj_set_align( ui_imuIndicator, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_imuIndicator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_imuIndicator, lv_color_hex(0x25FF09), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_imuIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imuStatus = lv_label_create(ui_Status1);
lv_obj_set_width( ui_imuStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imuStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imuStatus, 16 );
lv_obj_set_y( ui_imuStatus, -3 );
lv_obj_set_align( ui_imuStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_imuStatus,"Connected");

ui_Container9 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 781);
lv_obj_set_height( ui_Container9, 72);
lv_obj_set_x( ui_Container9, -41 );
lv_obj_set_y( ui_Container9, 0 );
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container7 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 177);
lv_obj_set_height( ui_Container7, 92);
lv_obj_set_x( ui_Container7, -254 );
lv_obj_set_y( ui_Container7, 15 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 32 );
lv_obj_set_y( ui_Label7, 1 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"roll");

ui_Container10 = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, 100);
lv_obj_set_height( ui_Container10, 50);
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rollValue = lv_label_create(ui_Container10);
lv_obj_set_width( ui_rollValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rollValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rollValue, -16 );
lv_obj_set_y( ui_rollValue, -1 );
lv_obj_set_align( ui_rollValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_rollValue,"0.00");
lv_obj_set_style_text_font(ui_rollValue, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 168);
lv_obj_set_height( ui_Container2, 76);
lv_obj_set_x( ui_Container2, -46 );
lv_obj_set_y( ui_Container2, 12 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"pitch");

ui_Container11 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, 100);
lv_obj_set_height( ui_Container11, 50);
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pitchValue = lv_label_create(ui_Container11);
lv_obj_set_width( ui_pitchValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pitchValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pitchValue, -16 );
lv_obj_set_y( ui_pitchValue, -1 );
lv_obj_set_align( ui_pitchValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_pitchValue,"0.00");
lv_obj_set_style_text_font(ui_pitchValue, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 152);
lv_obj_set_height( ui_Container3, 68);
lv_obj_set_x( ui_Container3, 237 );
lv_obj_set_y( ui_Container3, 4 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"yaw");

ui_Container12 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, 100);
lv_obj_set_height( ui_Container12, 50);
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_yawValue = lv_label_create(ui_Container12);
lv_obj_set_width( ui_yawValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yawValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_yawValue, -16 );
lv_obj_set_y( ui_yawValue, -1 );
lv_obj_set_align( ui_yawValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_yawValue,"0.00");
lv_obj_set_style_text_font(ui_yawValue, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_stats);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 773);
lv_obj_set_height( ui_Container5, 123);
lv_obj_set_x( ui_Container5, -1 );
lv_obj_set_y( ui_Container5, 53 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container5, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container5, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Status = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Status);
lv_obj_set_width( ui_Status, 141);
lv_obj_set_height( ui_Status, 40);
lv_obj_set_x( ui_Status, 313 );
lv_obj_set_y( ui_Status, -38 );
lv_obj_set_align( ui_Status, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Status, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Status, lv_color_hex(0xD3CDCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_encoderIndicator = lv_obj_create(ui_Status);
lv_obj_set_width( ui_encoderIndicator, 19);
lv_obj_set_height( ui_encoderIndicator, 21);
lv_obj_set_x( ui_encoderIndicator, -47 );
lv_obj_set_y( ui_encoderIndicator, -3 );
lv_obj_set_align( ui_encoderIndicator, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_encoderIndicator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_encoderIndicator, lv_color_hex(0x25FF09), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_encoderIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_encoderStatus = lv_label_create(ui_Status);
lv_obj_set_width( ui_encoderStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_encoderStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_encoderStatus, 16 );
lv_obj_set_y( ui_encoderStatus, -3 );
lv_obj_set_align( ui_encoderStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_encoderStatus,"Connected");

ui_Label12 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -223 );
lv_obj_set_y( ui_Label12, 21 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Distance Traveled");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_encoderValue = lv_label_create(ui_Container5);
lv_obj_set_width( ui_encoderValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_encoderValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_encoderValue, 50 );
lv_obj_set_y( ui_encoderValue, 21 );
lv_obj_set_align( ui_encoderValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_encoderValue,"0.0 cm");
lv_obj_set_style_text_font(ui_encoderValue, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Container5);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 35);
lv_obj_set_x( ui_Button5, 271 );
lv_obj_set_y( ui_Button5, 20 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label16 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Reset");

ui_Label11 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -298 );
lv_obj_set_y( ui_Label11, -39 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Encoder ");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_stats);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 773);
lv_obj_set_height( ui_Container6, 109);
lv_obj_set_x( ui_Container6, -4 );
lv_obj_set_y( ui_Container6, 178 );
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container6, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Status2 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Status2);
lv_obj_set_width( ui_Status2, 141);
lv_obj_set_height( ui_Status2, 40);
lv_obj_set_x( ui_Status2, 312 );
lv_obj_set_y( ui_Status2, -27 );
lv_obj_set_align( ui_Status2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Status2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Status2, lv_color_hex(0xD3CDCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiIndicator = lv_obj_create(ui_Status2);
lv_obj_set_width( ui_wifiIndicator, 19);
lv_obj_set_height( ui_wifiIndicator, 21);
lv_obj_set_x( ui_wifiIndicator, -47 );
lv_obj_set_y( ui_wifiIndicator, -3 );
lv_obj_set_align( ui_wifiIndicator, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_wifiIndicator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifiIndicator, lv_color_hex(0x25FF09), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifiIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiStatus = lv_label_create(ui_Status2);
lv_obj_set_width( ui_wifiStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiStatus, 16 );
lv_obj_set_y( ui_wifiStatus, -3 );
lv_obj_set_align( ui_wifiStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiStatus,"Connected");

ui_Label20 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -304 );
lv_obj_set_y( ui_Label20, 16 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"WIFI");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 35);
lv_obj_set_x( ui_Button1, 305 );
lv_obj_set_y( ui_Button1, 21 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Reconnect");

ui_Label23 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, -298 );
lv_obj_set_y( ui_Label23, -32 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"WIFI / Internet ");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

}
